Labels to barplot and heatmap
phovea/phovea_vis pull request #37
Opened 2017-03-10 13:21 UTC by katush

Add label to barplot and heatmap if there is enough space

2017-03-10 13:55 UTC, thinkh commented
One note: 
At the moment the text is overlaying the rect and thus prevents the selection of the row. In order to make the selection working, you need to add this lines of CSS:

```css
.phovea-heatmap { // for every vis type
  text {
    user-select: none;
    pointer-events: none;
  }
}
```

@katush Could you please add that to the default CSS?

2017-03-10 13:57 UTC, thinkh commented
Please also add some padding to label so that it's not so close at the border.

![vis-label-padding](https://cloud.githubusercontent.com/assets/5851088/23797789/c9bf571c-05a1-11e7-96e6-40f82ab05206.png)

2017-03-10 13:59 UTC, thinkh commented
And please add the labels also to the `phovea-histogram` and `phovea-mosaic`.

2017-03-10 14:02 UTC, thinkh commented
Additional request: Please take care that the font-size for a `phovea-list` and e.g., `phovea-heatmap` are equal for the same height.

![vis_match-font-sizes](https://cloud.githubusercontent.com/assets/5851088/23797945/945d4100-05a2-11e7-9cc1-d2eab3d3cb88.png)

2017-03-10 14:04 UTC, thinkh requested changes
Implementation looks fine for me. Just minor formatting issues.

2017-03-10 14:04 UTC, thinkh commented on src/heatmap/HeatMap1D.ts
> +       const rowHeight = this.size[1] / this.data.dim[0];
Incorrect line indent?

2017-03-10 14:04 UTC, thinkh commented on src/heatmap/HeatMap1D.ts
> +          height: (d) => rowHeight- padding
Space around minus

2017-03-10 15:46 UTC, katush commented
@thinkh I am not sure how to do this, `phovea-list` is just text within divs. This is svg, the scaling works differently. Any ideas?

> Please take care that the font-size for a `phovea-list` and e.g., `phovea-heatmap` are equal for the same height.

2017-03-10 19:04 UTC, thinkh commented
You can configure the initial scaling factor for the text (in the transform property) when you have both next to each other.

2017-03-11 00:26 UTC, katush commented
![image](https://cloud.githubusercontent.com/assets/8986080/23818228/9222298a-05f9-11e7-944c-578020333ef8.png)
 Should be done know. Though I consider moving the labels in histogram below it, same in filter view.

2017-03-13 18:09 UTC, thinkh commented
Thanks. Now it looks good 👍

2017-03-13 18:10 UTC, thinkh approved these changes

2017-03-13 18:10 UTC, merged